---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../common
- ../../type/small
  # site level addition
- ../../functions/network/n01

patchesStrategicMerge:
- ./versions.yaml
  # site level modification (patch)
- ./functions/network/n02/function.yaml

images:
- name: postgres
  newName: postgres
  newTag: 9.6.15

