apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  replicas: 1
  template:
    spec:
      containers:
      - args:
        - --enable-leader-election
        command:
        - /manager
        image: us.gcr.io/k8s-artifacts-prod/cluster-api/cluster-api-controller:v0.2.3
        name: manager
        resources:
          limits:
            memory: 100Mi
          requests:
            memory: 100Mi
      terminationGracePeriodSeconds: 10
