apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: test1
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.96.0.0/12
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: BareMetalCluster
    name: test1
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: BareMetalCluster
metadata:
  name: test1
  namespace: default
spec:
  cloudName: test1
  cloudsSecret:
    name: cloud-config
