apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfigTemplate
metadata:
  name: test1-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: baremetal
          name: '{{ ds.meta_data.hostname }}'
---
apiVersion: cluster.x-k8s.io/v1alpha2
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
    nodepool: nodepool-0
  name: test1-md-0
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: test1
      nodepool: nodepool-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: test1
        nodepool: nodepool-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
          kind: KubeadmConfigTemplate
          name: test1-md-0
          namespace: default
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: BareMetalMachineTemplate
        name: test1-md-0
        namespace: default
      version: v1.16.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: BareMetalMachineTemplate
metadata:
  name: test1-md-0
  namespace: default
spec:
  template:
    spec:
      bmc:
        address: libvirt://192.255.255.255:6233/
        credentialsName: worker-0-bmc-secret
      bootMACAddress: "00:00:00:00:00:00"
      image:
        checksum: 97830b21ed272a3d854615beb54cf004
        url: http://172.22.0.1/images/rhcos-ootpa-latest.qcow2
      online: false
      userData:
        name: worker-user-data
        namespace: openshift-machine-api
